<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $role }} Complaints Report</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }

        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 70px;
            height: 70px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 24px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }

        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            padding: 0 20px;
        }

        .details-table th, .details-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            color: #333;
        }

        .details-table th {
            font-weight: bold;
            background-color: #f7f7f7;
        }

        .section-title {
            font-size: 20px;
            color: #007bff;
            border-bottom: 2px solid #007bff;
            padding-bottom: 5px;
            margin-bottom: 15px;
            margin-top: 20px;
            padding-left: 20px;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #999;
        }

        table.complaints-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.complaints-table th,
        table.complaints-table td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }

        table.complaints-table th {
            background-color: #f5f5f5;
            font-weight: bold;
            text-transform: uppercase;
        }

        table.complaints-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <img src="data:image/png;base64,{{ $logoBase64 }}" alt="Clinic Logo">
        <h1>{{ $role }} Complaints Report</h1>
        <p>Generated by the PilarCare: Pilar College Clinic Management System</p>
    </div>

    <!-- Statistics Section -->
    <div class="section-title">Statistics</div>
    <table class="details-table">
        <tr>
            <th>Most Common Complaint</th>
            <td>{{ $mostCommonComplaint }} ({{ $commonComplaintCount }} occurrences)</td>
        </tr>
        <tr>
            <th>Most Used Medicine</th>
            <td>{{ $mostUsedMedicine }} ({{ $mostUsedMedicineCount }} occurrences)</td>
        </tr>
    </table>

    <!-- Complaints Table -->
    <div class="section-title">{{ $role }} Complaints</div>
    <table class="complaints-table">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Description of Sickness</th>
                <th>Pain Assessment</th>
                <th>Medicine Given</th>
                <th>Confine Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($complaints as $complaint)
                <tr>
                    <td>{{ $complaint->first_name }}</td>
                    <td>{{ $complaint->last_name }}</td>
                    <td>{{ $complaint->sickness_description }}</td>
                    <td>{{ $complaint->pain_assessment }}</td>
                    <td>{{ $complaint->medicine_given }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $complaint->confine_status)) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        This report was generated by the Pilar College Clinic Health System.
    </div>
</body>
</html>
