<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PilarCare Health Examination {{ $report_period }} Report</title>
    <style>
        /* General Styles */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            background-color: #ffffff;
        }

        /* Header Section */
        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 80px;
            height: 80px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 26px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 16px;
            color: #666;
        }

        /* Report Title */
        .report-title {
            text-align: center;
            font-size: 22px;
            color: #0056b3;
            margin-bottom: 20px;
        }

        /* Summary Section */
        .summary-section {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
        }

        .summary-box {
            background-color: #f7f7f7;
            padding: 15px 20px;
            border-radius: 8px;
            width: 30%;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }

        .summary-box h3 {
            margin: 0 0 10px 0;
            color: #28a745;
        }

        .summary-box p {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }

        /* Tables */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        table th, table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: left;
            color: #333;
        }

        table th {
            background-color: #007bff;
            color: white;
            font-weight: 600;
        }

        table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Footer Section */
        .footer {
            text-align: center;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            margin-top: 20px;
        }

        /* Responsive Design */
        @media (max-width: 600px) {
            .summary-section {
                flex-direction: column;
                align-items: center;
            }

            .summary-box {
                width: 80%;
                margin-bottom: 20px;
            }
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <img src="{{ $logoBase64 }}" alt="Logo">
        <h1>PilarCare Health Examination {{ $report_period }} Report</h1>
        <p>Generated by Pilar College Clinic Management System</p>
    </div>

    <!-- Report Title -->
    <div class="report-title">
        <h2>{{ $report_period }} Report as of {{ $report_date }}</h2>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
        <div class="summary-box">
            <h3>Total Examinations</h3>
            <p>{{ $totalExaminations }}</p>
        </div>
        <div class="summary-box">
            <h3>Unique Students</h3>
            <p>{{ $uniqueStudents }}</p>
        </div>
    </div>

    <!-- Health Examinations Data Table -->
    <div>
        <h2>Health Examinations Details</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Student Name</th>
                    <th>ID Number</th>
                    <th>School Year</th>
                    <th>Submission Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($healthExaminations as $exam)
                    <tr>
                        <td>{{ $exam->id }}</td>
                        <td>{{ $exam->user->first_name }} {{ $exam->user->last_name }}</td>
                        <td>{{ $exam->user->id_number }}</td>
                        <td>{{ $exam->school_year }}</td>
                        <td>{{ $exam->created_at->format('Y-m-d H:i') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Additional Sections (Charts, Analysis, etc.) can be added here -->

    <!-- Footer Section -->
    <div class="footer">
        <p>&copy; {{ date('Y') }} PilarCare Clinic. All rights reserved.</p>
    </div>
</body>
</html>
