<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PilarCare Inventory Statistics Report</title>
    <style>
        /* General Styles */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            background-color: #ffffff;
        }

        /* Header Section */
        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 80px;
            height: 80px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 26px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 16px;
            color: #666;
        }

        /* Report Title */
        .report-title {
            text-align: center;
            font-size: 22px;
            color: #0056b3;
            margin-bottom: 20px;
        }

        /* Summary Section */
        .summary-section {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
        }

        .summary-box {
            background-color: #f7f7f7;
            padding: 15px 20px;
            border-radius: 8px;
            width: 30%;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }

        .summary-box h3 {
            margin: 0 0 10px 0;
            color: #28a745;
        }

        .summary-box p {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }

        /* Tables */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        table th, table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: left;
            color: #333;
        }

        table th {
            background-color: #007bff;
            color: white;
            font-weight: 600;
        }

        table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Footer Section */
        .footer {
            text-align: center;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            margin-top: 20px;
        }

        /* Charts */
        .chart-section {
            margin-bottom: 30px;
        }

        /* Responsive Design */
        @media (max-width: 600px) {
            .summary-section {
                flex-direction: column;
                align-items: center;
            }

            .summary-box {
                width: 80%;
                margin-bottom: 20px;
            }
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
    <img src="data:image/png;base64,{{ $logoBase64 }}" alt="Logo">

        <h1>PilarCare Inventory Statistics Report</h1>
        <p>Generated by Pilar College Clinic Management System</p>
    </div>

    <!-- Report Title -->
    <div class="report-title">
        <h2>{{ $report_period }} Report: {{ $report_date }}</h2>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
        <div class="summary-box">
            <h3>Total Inventory Items</h3>
            <p>{{ $totalItems }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Quantity</h3>
            <p>{{ $totalQuantity }}</p>
        </div>
    </div>

    <!-- Inventory Data Table -->
    <div>
        <h2>Inventory Details</h2>
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Brand</th>
                    <th>Type</th>
                    <th>Date Acquired</th>
                    <th>Expiry Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($inventoryData as $item)
                    <tr>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ $item->quantity }}</td>
                        <td>{{ $item->supplier }}</td>
                        <td>{{ $item->type }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->date_acquired)->format('Y-m-d') }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->expiry_date)->format('Y-m-d') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Most Used Items Table -->
    <div>
        <h2>Most Used Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Total Quantity Used</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($mostUsedItems as $item)
                    <tr>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ $item->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Reorder Recommendations Table -->
    <div>
        <h2>Reorder Recommendations</h2>
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Current Quantity</th>
                    <th>Suggested Reorder Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reorderRecommendations as $item)
                    <tr>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ $item->quantity }}</td>
                        <td>
                            @php
                                // Example: Suggested reorder quantity based on type
                                $suggested = $item->type === 'Medicine' ? ceil($item->quantity * 4) : ceil($item->quantity * 2);
                            @endphp
                            {{ $suggested }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Expiring Soon Items Table -->
    <div>
        <h2>Expiring Soon Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Expiry Date</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($expiringSoon as $item)
                    <tr>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ \Carbon\Carbon::parse($item->expiry_date)->format('Y-m-d') }}</td>
                        <td>{{ $item->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Charts Section -->

    <!-- Footer Section -->
    <div class="footer">
        <p>&copy; {{ date('Y') }} PilarCare Clinic. All rights reserved.</p>
    </div>
</body>
</html>



