<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pilar Care Medical Record Report</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }

        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 70px;
            height: 70px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 24px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }

        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            padding: 0 20px;
        }

        .details-table th, .details-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            color: #333;
        }

        .details-table th {
            font-weight: bold;
            background-color: #f7f7f7;
        }

        .section-title {
            font-size: 20px;
            color: #007bff;
            border-bottom: 2px solid #007bff;
            padding-bottom: 5px;
            margin-bottom: 15px;
            margin-top: 20px;
            padding-left: 20px;
        }

        .profile-picture {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

        .profile-picture img {
            border-radius: 50%;
            width: 100px;
            height: 100px;
            object-fit: cover;
            border: 3px solid #007bff;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #999;
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <img src="{{ $logoBase64 }}" alt="Clinic Logo">
        <h1>Clinic Medical Record Report</h1>
        <p>Generated by the PilarCare: Pilar College Clinic Management System</p>
    </div>

    <!-- Patient Profile Picture Section -->
    <table class="details-table">
        <thead>
            <tr>
                <th>Detail</th>
                <th>Information</th>
            </tr>
        </thead>
        <tbody>
        <tr>
                <td><strong>Profile Picture:</strong></td>
                <td>
                    @if ($profilePictureBase64)
                        <img src="{{ $profilePictureBase64 }}" alt="Profile Picture" style="border-radius: 50%; width: 80px; height: 80px; object-fit: cover; border: 2px solid #007bff;">
                    @else
                        <p>No profile picture available.</p>
                    @endif
                </td>
            </tr>
            <tr>
                <td><strong>Name:</strong></td>
                <td>{{ $medicalRecord->name }}</td>
            </tr>
            <tr>
                <td><strong>Age:</strong></td>
                <td>{{ $medicalRecord->age }}</td>
            </tr>
            <tr>
                <td><strong>Birthdate:</strong></td>
                <td>{{ $medicalRecord->birthdate }}</td>
            </tr>
            <tr>
                <td><strong>Address:</strong></td>
                <td>{{ $medicalRecord->address }}</td>
            </tr>
            <tr>
                <td><strong>Contact Number:</strong></td>
                <td>{{ $medicalRecord->personal_contact_number }}</td>
            </tr>
            <tr>
                <td><strong>Emergency Contact:</strong></td>
                <td>{{ $medicalRecord->emergency_contact_number }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Medical History Section -->
    <div class="section-title">Medical History</div>
    <table class="details-table">
        <thead>
            <tr>
                <th>Medical Information</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>Past Illnesses:</strong></td>
                <td>{{ $medicalRecord->past_illness }}</td>
            </tr>
            <tr>
                <td><strong>Chronic Conditions:</strong></td>
                <td>{{ $medicalRecord->chronic_conditions }}</td>
            </tr>
            <tr>
                <td><strong>Surgical History:</strong></td>
                <td>{{ $medicalRecord->surgical_history }}</td>
            </tr>
            <tr>
                <td><strong>Family Medical History:</strong></td>
                <td>{{ $medicalRecord->family_medical_history }}</td>
            </tr>
            <tr>
                <td><strong>Allergies:</strong></td>
                <td>{{ $medicalRecord->allergies }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Physical Examination Section -->
    <div class="section-title">Physical Examination</div>
    <table class="details-table">
        <thead>
            <tr>
                <th>Physical Examination Details</th>
                <th>Information</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>Height:</strong></td>
                <td>{{ $physicalExamination->height }}</td>
            </tr>
            <tr>
                <td><strong>Weight:</strong></td>
                <td>{{ $physicalExamination->weight }}</td>
            </tr>
            <tr>
                <td><strong>Vision:</strong></td>
                <td>{{ $physicalExamination->vision }}</td>
            </tr>
            <tr>
                <td><strong>Remarks:</strong></td>
                <td>{{ $physicalExamination->remarks }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        This report was generated by the Pilar College Clinic Health System.
    </div>
</body>
</html>