<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pilar Care Medical Record Report</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }

        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 70px;
            height: 70px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 24px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }

        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            padding: 0 20px;
        }

        .details-table th, .details-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            color: #333;
        }

        .details-table th {
            font-weight: bold;
            background-color: #f7f7f7;
        }

        .section-title {
            font-size: 20px;
            color: #007bff;
            border-bottom: 2px solid #007bff;
            padding-bottom: 5px;
            margin-bottom: 15px;
            margin-top: 20px;
            padding-left: 20px;
        }

        .profile-picture {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

        .profile-picture img {
            border-radius: 50%;
            width: 100px;
            height: 100px;
            object-fit: cover;
            border: 3px solid #007bff;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #999;
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        @if(isset($logoBase64))
            <img src="data:image/png;base64,{{ $logoBase64 }}" alt="Clinic Logo">
        @endif
        <h1>Clinic Slip</h1>
        <p>Generated by PilarCare: Pilar College Clinic Management System</p>
    </div>

    <!-- Profile Picture (Optional) -->
    @if(isset($complaint->profile_picture))
        <div class="profile-picture">
            <img src="{{ $complaint->profile_picture }}" alt="Profile Picture">
        </div>
    @endif

    <!-- Details Table -->
    <table class="details-table">
        <tr>
            <th>First Name</th>
            <td>{{ $complaint->first_name }}</td>
        </tr>
        <tr>
            <th>Last Name</th>
            <td>{{ $complaint->last_name }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ $complaint->age }}</td>
        </tr>
        <tr>
            <th>Birthdate</th>
            <td>{{ $complaint->birthdate }}</td>
        </tr>
        <tr>
            <th>Personal Contact Number</th>
            <td>{{ $complaint->personal_contact_number }}</td>
        </tr>

        <!-- Role-Specific Data -->
        @if($role == 'student')
            <tr>
                <th>Grade</th>
                <td>{{ $grade ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>Section</th>
                <td>{{ $section ?? 'N/A' }}</td>
            </tr>
        @elseif($role == 'staff')
            <tr>
                <th>Position</th>
                <td>{{ $position ?? 'N/A' }}</td>
            </tr>
        @elseif($role == 'teacher')
            <tr>
                <th>BED or HED</th>
                <td>{{ $bed_or_hed ?? 'N/A' }}</td>
            </tr>
        @endif

        <!-- Common Complaint Data -->
        <tr>
            <th>Pain Assessment</th>
            <td>{{ $complaint->pain_assessment }}</td>
        </tr>
        <tr>
            <th>Medicine Given</th>
            <td>{{ $complaint->medicine_given }}</td>
        </tr>
        <tr>
            <th>Description of Sickness</th>
            <td>{{ $complaint->sickness_description }}</td>
        </tr>
        <tr>
            <th>Confine Status</th>
            <td>{{ ucfirst($complaint->confine_status) }}</td>
        </tr>
        <tr>
            <th>Go Home Status</th>
            <td>{{ ucfirst($complaint->go_home) }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ ucfirst($complaint->status) }}</td>
        </tr>
    </table>

    <!-- Additional Sections (Optional) -->
    @if(!empty($complaint->additional_info))
        <div class="section-title">Additional Information</div>
        <p style="padding-left: 20px;">{{ $complaint->additional_info }}</p>
    @endif

    <!-- Footer -->
    <div class="footer">
        PilarCare © {{ date('Y') }}. All rights reserved.
    </div>
</body>
</html>