<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PilarCare Appointment Statistics Report</title>
    <style>
        /* General Styles */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            background-color: #ffffff;
        }

        /* Header Section */
        .header {
            text-align: center;
            padding: 20px;
            border-bottom: 2px solid #007bff;
            margin-bottom: 20px;
        }

        .header img {
            width: 80px;
            height: 80px;
            margin-bottom: 10px;
        }

        .header h1 {
            margin: 5px 0;
            font-size: 26px;
            color: #333;
        }

        .header p {
            margin: 0;
            font-size: 16px;
            color: #666;
        }

        /* Report Title */
        .report-title {
            text-align: center;
            font-size: 22px;
            color: #0056b3;
            margin-bottom: 20px;
        }

        /* Summary Section */
        .summary-section {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
        }

        .summary-box {
            background-color: #f7f7f7;
            padding: 15px 20px;
            border-radius: 8px;
            width: 30%;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }

        .summary-box h3 {
            margin: 0 0 10px 0;
            color: #28a745;
        }

        .summary-box p {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }

        /* Appointments Table */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        table th, table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: left;
            color: #333;
        }

        table th {
            background-color: #007bff;
            color: white;
            font-weight: 600;
        }

        table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Footer Section */
        .footer {
            text-align: center;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            margin-top: 20px;
        }

        /* Responsive Design */
        @media (max-width: 600px) {
            .summary-section {
                flex-direction: column;
                align-items: center;
            }

            .summary-box {
                width: 80%;
                margin-bottom: 20px;
            }
        }
    </style>
</head>
<body>
    <!-- Header Section -->
    <div class="header">
        <img src="data:image/png;base64,{{ $logoBase64 }}" alt="Logo">
        <h1>PilarCare Appointment Statistics Report</h1>
        <p>Generated by Pilar College Clinic Management System</p>
    </div>

    <!-- Report Title -->
    <div class="report-title">
        <h2>{{ $period }} Report: {{ $startDate }} to {{ $endDate }}</h2>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
        <div class="summary-box">
            <h3>Total Appointments</h3>
            <p>{{ $totalAppointments }}</p>
        </div>
        <div class="summary-box">
            <h3>Completed Appointments</h3>
            <p>{{ $completedAppointments }}</p>
        </div>
        <div class="summary-box">
            <h3>Upcoming Appointments</h3>
            <p>{{ $upcomingAppointments }}</p>
        </div>
    </div>

    <!-- Appointments Table -->
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Patient Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Type</th>
                <th>Doctor</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($appointments as $index => $appointment)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $appointment->patient_name }}</td>
                    <td>{{ \Carbon\Carbon::parse($appointment->appointment_date)->format('M d, Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A') }}</td>
                    <td>{{ $appointment->appointment_type }}</td>
                    <td>{{ $appointment->doctor->user->first_name }} {{ $appointment->doctor->user->last_name }}</td>
                    <td>
                        @if ($appointment->status === 'confirmed')
                            <span style="color: #28a745; font-weight: bold;">Confirmed</span>
                        @else
                            <span style="color: #ffc107; font-weight: bold;">Pending</span>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer Section -->
    <div class="footer">
        <p>&copy; {{ date('Y') }} PilarCare Clinic. All rights reserved.</p>
    </div>
</body>
</html>
